### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [j-hc/VolumeTile#2]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
@j-hc any word?

**Comment by j-hc** [comment]
sure. updated and uploaded a signed build.

**Comment by IzzySoft** [comment]
Thanks! Integrated, and the new cert pinned. Update protocol:

```
$ iod repo get com.jhc.volumetile
com.jhc.volumetile: looking for 'https://api.github.com/repos/j-hc/VolumeTile/releases'
com.jhc.volumetile: checking tag '2'
com.jhc.volumetile: lastRelNo set to '2', checking for files
com.jhc.volumetile: Upstream file date (2024-02-20 20:11) is newer than ours (2023-04-15 13:35).
com.jhc.volumetile: returning ['2','https://github.com/j-hc/VolumeTile/releases/download/2/app-release.apk',1708456269]
com.jhc.volumetile: 1/2, https://github.com/j-hc/VolumeTile/releases: https://github.com/j-hc/VolumeTile/releases/download/2/app-release.apk
- Grabbing update for com.jhc.volumetile: OK
- Checking 'repo/com.jhc.volumetile_2.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
! repo/com.jhc.volumetile_2.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

If you want to get rid of that `DEPENDENCY_INFO_BLOCK` blob, that's easy:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

And if you want an icon to be shown, please point me to it :wink:

![image](https://github.com/j-hc/VolumeTile/assets/6781438/3f1674ab-fc12-4615-b788-eb7f77cff94f)
